### ISSUE TITLE
How to install integration

### ISSUE THREAD

**Issue by Vungr** [rnovacek/homeassistant_cz_energy_spot_prices#11]
Hello, I have problem with instalation this integration.
I did everything according manual, but point 4 stuck me.
I have not found "Czech Energy Spot Prices" integratin in Settings -> Devices & Services -> Integration.

What can be wrong?

**Comment by rnovacek** [comment]
Could you run this command in your `config` directory:

```
ls -la custom_components/cz_energy_spot_prices/
```

You should see a couple of files there, for example `sensor.py`.

**Comment by rnovacek** [comment]
It's now possible to install directly from HACS, so closing.
