### ISSUE TITLE
HA a Energie

### ISSUE THREAD

**Issue by mitchmb** [rnovacek/homeassistant_cz_energy_spot_prices#14]
Zdravím,
Integrace je super. Jen jsem si všiml jedné věci. V když v HA používám kartu energie a dob záložky spotřeba že sítě si přidám aktuální cenu v dané hodině, tak to ale počítá o hodinu jinak.
Protože HA tam tu energii za poslední hodinu přidává na začátku další hodiny, ale mezitím už se v senzoru aktuální ceny právě změnila cena na tu další hodinu.
Zatím jsem to vyřešil pomocným sensorem, který se aktualizuje o minutu zpožděně oproti vašemu, aby HA měl ještě tu cenu minulé hodiny.
Jen takový poznatek .

Martin

**Comment by rnovacek** [comment]
Díky za nahlášení. Moc mě nenapadá, jak to řešit. Připadá mi hloupé posunout změnu ceny o minutu, protože pak by to nesedělo pro automatizace (nechceme zapínat a vypínat spotřebiče o minutu později).

Mohl bych poprosit o screenshot, jak máte nastavené?

**Comment by mitchmb** [comment]
Chápu, ale zase na druhou stranu pokud použiju sensor.current_spot_electricity_price pro určení cenu pro danou hodinu v energetickém panelu HA, tak HA zapisuje uplynulou hodinu až v celou následující hodinu. Tedy např. rozmezí 10-11h zapíše v 11:00, ale v sensor.current_spot_electricity_price už je aktuální cena pro 11h. Ale já v ten okamžik potřebuji mít cenu předchozí hodiny tedy 10h. Vyřešil jsem to tedy tak, že jsem si v nastavení HA vytvořil pomocnou entitu input_number do které pomocí noderedu zapisuji novou cenu s minutovým zpožděním. Docílím tak toho, že v 11:00 tam mám ještě cenu 10h. Zpožděný zápis by šel udělat i pomocí normální automatizace, ale já osobně spíš používám NodeRed, protože mi nabízí víc možností.

Takže by možná bylo řešením vytvořit entitu např. sensor.current_spot_electricity_price_delayed do které by se hodnota zapisovala zpožděně. A tato entita by se používala pro energetický panel HA.

![Poznámka 2023-03-20 183610](https://user-images.githubusercontent.com/33593056/226422023-10072f33-ede1-4f06-b54d-09e5438f4927.png)

**Comment by zejdajan** [comment]
@mitchmb  Zdravím, řeším podobný problém a Vaše řešení je asi nejlepší. 
Mohl bych Vás poprosit o screen nastavení 1. a 3. bloku z NodeRED? Zatím jsem NodeRED nepoužíval, takže spíš zkouším.
Díky

**Comment by mitchmb** [comment]
@zejdajan nic na tom není :-)
![1](https://user-images.githubusercontent.com/33593056/230963384-129124e6-f2cd-4680-b9f9-f612925f7e10.png)
![3](https://user-images.githubusercontent.com/33593056/230963390-fe1ebcbe-4841-47fc-a041-bb294cef9102.png)

**Comment by zejdajan** [comment]
@mitchmb Díky, měl jsem špatně "data" pro zpožděnou cenu.

**Comment by Brectan** [comment]
Dobrý den, integrace je super věc, klobouk dolu. Chci se jen zeptat jak mám chápat dodatečné náklady na energii. Je to za kWh nebo jednotná částka? Děkuji
![image](https://user-images.githubusercontent.com/89406324/233447043-487fae8e-12dd-4e69-a82c-9ded68dd1554.png)

**Comment by rnovacek** [comment]
Dodatečné náklady ještě nefungují, omlouvám se.

Zpožděnou cenu přidám.

**Comment by rnovacek** [comment]
Můžete mi prosím někdo vysvětlit (třeba @mitchmb), jak jste přišli na to, že se ty ceny zpožďují? Trochu jsem se v tom vrtal a přijde mi, že to ty statistiky pro energie v Energy Dashboardu dělá plynule, nikoli skokově jednou za hodinu, takže by to problém být neměl.

Tohle je graf exportu do sítě, ceny za dodávku a hodinové ceny:
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/618886/2192d2bb-07a3-4bce-8bbf-28ed4308b14e)

**Comment by mitchmb** [comment]
Aktuální graf je něco jiného. Energy monitor funguje tak, že máte entitu kde je aktuální spotřeba. Vždy v celou hodinu si vezme aktuální hodnotu té entity a uloží si jí. Další celou hodinu zase vezme aktuální hodnotu a jen vypočítá rozdíl mezi poslední a předposlední. Tím získá spotřebu za uplynulou hodinu. A tady nastává problém s cenou, protože to dělá v celou novou hodinu, ale při použití aktuální ceny z integrace už je to cena za aktuální hodinu. Ale já tu spotřebu za uplynulou hodinu potřebuji vynásobit cenou za minulou hodinu. Proto jsem šel cestou zpožděné aktuální ceny, aby energy monitor měl v nějaké entitě cenu té minulé hodiny. Stačí si to ověřit tak že si to vypočítáte na kalkulačce sám. Vemte nějakou hodinu kde bude větší cenový rozdíl za kWh. A uvidíte že při použití ceny z integrace to nebude sedět.

**Comment by rnovacek** [comment]
Asi mi něco uniká, kde najdu ten energy monitor? Jediné místo, kde vidím cenu, je Energy Dashboard, ale tam je cena za aktuální období (den, týden, měsíc, rok), cenu po hodinách nikde nevidím.

![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/618886/1ed084d3-16fb-45da-8ee6-45cfff8909f7)

**Comment by mitchmb** [comment]
Energy monitor myslím samozřejmě energy dashboard. Ve vašem obrázku je sice cena za den, ale ta se samozřejmě v daném dni každou hodinu zvýší o spotřebu za uplynulou hodinu. A sledování po hodině lze zjistit že to počítá špatně.

**Comment by mitchmb** [comment]
V podstatě by stačilo vytvořit senzor s názvem např. "Cena minulé hodiny pro Energy Dashboard" ve které se bude ukládat cena minulé hodiny a tento sensor se použije pro Energy Dashboard

**Comment by radoslavius** [comment]
A to nemluve o tom, kdyz nejakou dobu HA nejede, pak to po nasledujici cele hodine vezme vsechno sakumprask za aktualni cenu v nastavene entite. Ukazka kdyz jsem v nedeli prenasel HA na nove zelezo:
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/3509024/6df1a8e5-4f6a-4caa-8551-ed94a6b8fcf4)
Toto sice bezne nenastava, ale je krasne videt jak funguje nacitani dat do dashboardu. A tak funguje i vypocitavani ceny. Po uplynuti kazde cele hodiny se spusti nejaky trigger, ktery to spocita a nastavi, ale entita uz tou dobou vraci cenu za dalsi hodinu a tak je vypocet spatne.

**Comment by rnovacek** [comment]
Ta vstupní entita (spotřeba energie) se mění jen jednou za hodinu? Neměla by se měnit kontinuálně a při každé změně se vynásobit cenou pro danou hodinu? Co kdyby nebyly na spotu ceny za hodinu ale za půlhodinu (či jiný interval)? Pak by to taky nefungovalo, ne? (nevědělo by se, kolik se spotřebovalo za první půlhodinu a kolik za druhou)

Já to mám takhle:
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/618886/7ee3bee5-3278-4e0e-9cdb-f9885c1cbf65)

a vstupní entita stoupá lineárně (žádné skoky):
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/618886/ab8dbc53-1aa0-46e9-a5c4-980e135cb637)

@radoslavius tohle asi řešení nemá, vstupní entita má skok v datech, je tam pořád hodnota, kdy se to vypnulo a pak najednou je ta nová. Nejsou tam data v kterou hodinu se kolik spotřebovalo, takže až se objeví nová hodnota, vezme se aktuální hodinová cena a ta se použije. Z hlediska HA všechna spotřeba proběhla v momentě nového startu.

**Comment by radoslavius** [comment]
Neznam presne postup jak to HA dela, ale mam vysledovano, ze v energy dashboardu se vzdy hodnoty naplni po uplynuti kazde cele hodiny. Z toho se da soudit, ze informace o cenach teda pocita taky v tu dobu. Udaje se tam zapisou a uz se pak nikdy neprepocitavaji. Takze se vezme aktualne nastavena hodnota v entite v tu chvili.

Pokud by se cena menila v mensim casovem useku nez hodina, tak by se to pomoci energy dashboardu v HA resilo dost blbe. To by sis asi musel nejak pocitat prubezne a do te entity s cenou pak vlozit nejaky vypocteny prumer.

To co jsem posilal urcite nema reseni, jen jsem na tom chtel demonstrovat jak ten dashboard funguje. A tak jak zapise spotrebu a vyrobu, tak v tu stejnou chvili i cenu a tim padem cenu za aktualni hodinu a ne za tu predeslou, kdy ta spotreba/vyroba vznikla.

**Comment by rnovacek** [comment]
To, že se to v energy dashboardu objeví až v celou hodinu nic neříká o tom, jak se to počítá. Očekával bych, že se to bude počítat průběžně, protože energy dashboard neví, kdy se mění hodinová cena. Je to jen další vstupní entita.

**Comment by rnovacek** [comment]
@mitchmb Můžete mi sem prosím hodit screenshot grafu té vstupní entity, kterou máte v energy dashboardu? Podobně, jak jsem postoval v tomhle [komentáři](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/issues/14#issuecomment-1709612055)?

**Comment by radoslavius** [comment]
Momentalne jsem v ocekavani na prechod na spotove ceny, takze ted tam mam nejakou moji entitu s fixni cenou, ale prubezne studuju jak a co kde nastavit, abych mohl naskocit. Zvazuju, ze bych si nahodil nejaky testovaci HA, kde bych si to uz nastavil na spotove ceny, takze jak to bude, tak muzu testovat.

![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/3509024/0108132c-9fe7-4cd8-bdac-c0c48b87afdf)

Co se tyka te vstupni hodnoty, tak to sice stoupa linearne, ale ten dashboard to pocita podle me z rozdilu kazdou hodinu. Takze pokud je ma uvaha spravna, tak kdyz bude skoro celou hodinu nastavena cena na 0 a pak to pred uplynutim hodiny nastavite, tak se to vypocita s tou nastavenou cenou. Naopak kdyz cenu na prelomu hodiny nastavite na 0, tak to spocita 0. Nicmene v tom cenovem prehledu to je za cely den, takze to uvidite jen v pripade velkeho cenoveho skoku.

**Comment by mitchmb** [comment]
> @mitchmb Můžete mi sem prosím hodit screenshot grafu té vstupní entity, kterou máte v energy dashboardu? Podobně, jak jsem postoval v tomhle [komentáři](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/issues/14#issuecomment-1709612055)?

Tak nějak úplně nechápu co přesně teď řešíte? Pokud chcete, aby se spotové ceny počítaly správně. Je potřeba mít entitu, kde bude uložená cena předchozí hodinyva tu používat v energy dasboardu. Ale to už jsem všechno tady vysvětloval.
![Screenshot_2023-09-07-10-44-12-133_io homeassistant companion android](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/33593056/87ceddcd-a105-4c4e-ab91-0df7c153409d)

**Comment by mitchmb** [comment]
> Co se tyka te vstupni hodnoty, tak to sice stoupa linearne, ale ten dashboard to pocita podle me z rozdilu kazdou hodinu. Takze pokud je ma uvaha spravna, tak kdyz bude skoro celou hodinu nastavena cena na 0 a pak to pred uplynutim hodiny nastavite, tak se to vypocita s tou nastavenou cenou. Naopak kdyz cenu na prelomu hodiny nastavite na 0, tak to spocita 0. Nicmene v tom cenovem prehledu to je za cely den, takze to uvidite jen v pripade velkeho cenoveho skoku.

Ano HA spočítá rozdíl odběru v předešlé hodině (protože to počítá na začátku nové hodiny). A tento rozdíl je potřeba vynásobit s cenou právě v té minulé hodině. Takže jak už jsem tady vysvětloval, udělal jsem si entitu, která je oproti originální entitě s aktuální cenou o minutu zpožděná. Tedy aktuální cena se do ní uloží v celou hodinu a 1 minutu. Nicméně to stačí protože přesně v celou hodinu se provede výpočet a ještě tam je vlastně cena předchozí hodiny, takže vše sedí. A v Energy dashboardu se ukazuje pouze cena za celý den, takže pokud chcete zjistit jestli to počítá správně musíte si to sledovat po hodině. Ale takhle jak jsem to udělal já je to správně.

**Comment by radoslavius** [comment]
@mitchmb Jen jsem doplnoval info pro @rnovacek , protoze mam pocit, ze tuto realitu "nechce prijmout" ;)
@rnovacek nic ve zlem

**Comment by mitchmb** [comment]
@radoslavius aha, jinak ano HA funguje na rozdílu stavů před a po. Ale pokud mezitím vypadne třeba elektřina nebo nefunguje HA, tak se výpočet provede pro další hodině, kdy už to nemusí souhlasit. Prostě tak to je.

**Comment by rnovacek** [comment]
Pokud to HA počítá jednou za hodinu a to až v následující hodině, tak to podle mě dělá špatně. Co když se bude cena za energii měnit častěji než jednou za hodinu? Možná by stálo za to na to založit issue v repozitáři HomeAssistantu.

**Comment by mitchmb** [comment]
@rnovacek tak spotové ceny jsou také po hodině. Takže bych to teď vůbec neřešil, protože to teď je správně.

**Comment by radoslavius** [comment]
ale asi se to bude muset resit ...
https://ekonomickydenik.cz/trh-s-elektrinou-se-vyrazne-zmeni-co-prinese-v-praxi-obchodovani-po-15-minutach/
😄 
pokud to neni vtip

**Comment by davidrapan** [comment]
Zdravím, sice je to rok a půl starý téma, ale zaujalo mě to. Nevím teda jestli HA tehdy nedělal něco jinak. Ale teď určitě nic skokově nepočítá, jen to skokově po hodině ukazuje. ;) Na sensor, který řeší ten cost co Energy Dashboard ukazuje se i dá v Developer Tools mrknout a jde na něm vidět, že nabíhá postupně.

Páčko 😆

**Comment by rnovacek** [comment]
Díky @davidrapan. Myslím, že tohle issue můžem zavřít.
