### ISSUE TITLE
Přestupné dny

### ISSUE THREAD

**Issue by flajzi** [rnovacek/homeassistant_cz_energy_spot_prices#17]
Našel jsem chybu v zítřejším (tj. 26.3.) dni, kdy se posouvá čas. Podobný problém bude možná i na podzim.
V grafu zobrazení cen vidím sice správně sloupec 1:00, poté 3:00, ale zmizí cena jedné hodiny, takže všechny hodinové ceny po 3:00 (včetně) jsou posunuté o jednu hodinu.

**Comment by rnovacek** [comment]
Díky za nahlášení. Je to snad opraveno v https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/commit/e60e41bed6318a505ac5455bd6d9a515800237d0.

**Comment by flajzi** [comment]
Po opravě jsem našel ještě jednu chybu, nevím, jestli je to chyba integrace nebo karty apexcharts, ale značka "Now" ukazuje o hodinu napřed. Viz screenshot (bráno v 11:52).
![image](https://user-images.githubusercontent.com/6259367/227768186-66a5aeaf-a268-4aae-a77a-34d61e09b8dc.png)
