### ISSUE TITLE
sensor.spot_electricity_is_cheapest ON od 12:00 dosud

### ISSUE THREAD

**Issue by 02curls** [rnovacek/homeassistant_cz_energy_spot_prices#18]
mám [0.3.0]
sensor.spot_electricity_is_cheapest je dnes od 12:00 dosud zapnutý:
<img width="539" alt="Screenshot 2023-03-26 at 19 09 43" src="https://user-images.githubusercontent.com/107803294/227792291-78f2c1eb-72ec-4ae0-a5e0-8573a788da7d.png">

ostatní bloky vypadají normálně:
<img width="329" alt="Screenshot 2023-03-26 at 19 12 44" src="https://user-images.githubusercontent.com/107803294/227792430-190d0454-b338-46c4-8397-b1671b2d9084.png">

**Comment by rnovacek** [comment]
Můžete se prosím podívat do logů, jestli tam není nějaká chybová hláška? Také zkuste verzi 0.3.1. Díky.

**Comment by 02curls** [comment]
upgraded na 0.3.1. a vše je v pořádku, díky moc

v lozích bylo ještě před upgradem na 0.3.1. toto:

Logger: custom_components.cz_energy_spot_prices.coordinator
Source: custom_components/cz_energy_spot_prices/coordinator.py:103
Integration: Czech Energy Spot Prices (documentation, issues)
First occurred: 13:00:03 (7 occurrences)
Last logged: 19:00:02

Unexpected error fetching Czech Energy Spot Prices data: 2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 168, in _async_update_data
    return SpotRateData(rates, zoneinfo)
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 103, in __init__
    for i, hour in enumerate(sorted(self.tomorrow_day.hours_by_dt.values(), key=lambda hour: hour._consecutive_sum_prices[consecutive]), 1):
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 103, in <lambda>
    for i, hour in enumerate(sorted(self.tomorrow_day.hours_by_dt.values(), key=lambda hour: hour._consecutive_sum_prices[consecutive]), 1):
KeyError: 2

**Comment by rnovacek** [comment]
Tak snad opraveno. Díky za nahlášení.
