### ISSUE TITLE
Nenačítá ceny z OTE po 26.3.2023

### ISSUE THREAD

**Issue by gut1986** [rnovacek/homeassistant_cz_energy_spot_prices#20]
Zdravím. Do včerejška tj. 26.3.2023 aplikace načítala ceny z OTE v pořádku. Dnes 27.3.2023 již aktuální ceny nenačetla. Poslední načtený údaj mám 26.3.2023 22:00. Jsem začátečník, takže neumím blíže popsat, kde je problém. Díky.

**Comment by mitchmb** [comment]
Zkuste jestli máte poslední verzi 0.3.1 a jestli ano, tak počkejte do odpoledne. Já dnešní údaje mám.
![Uploading Screenshot_2023-03-27-11-48-19-932-edit_io.homeassistant.companion.android.jpg…]()

**Comment by rnovacek** [comment]
Podívejte se prosím do logů - Settings -> System -> Logs -> Tlačítko "Load full logs" a nahrejte to sem. A jak říká @mitchmb,  zkontrolujte prosím verzi.

**Comment by gut1986** [comment]
Neměl jsem aktuální verzi. Zatím se s Home assistant učím :-) Po aktualizaci to jede. Sorry za zbytečný příspěvek.

**Comment by rnovacek** [comment]
Žádný problém, aktualizace vyšla teprve včera.
