### ISSUE TITLE
HA update 2023.5.2

### ISSUE THREAD

**Issue by davidvalasek** [rnovacek/homeassistant_cz_energy_spot_prices#22]
Dobrý den, po updatu mi píše HA 

This entity (sensor.current_spot_electricity_price) is no longer being provided by the cz_energy_spot_prices integration. If the entity is no longer in use, delete it in settings.

Poradíte prosím?

Děkuji.

**Comment by rnovacek** [comment]
Žádný problém u sebe nevidím, můžete se prosím podívat do logů? Je to v System -> Settings -> Logs.

**Comment by davidvalasek** [comment]
Logger: homeassistant.config_entries
Source: custom_components/cz_energy_spot_prices/__init__.py:24

Error setting up entry Electricity Spot Rate in CZK/kWh for cz_energy_spot_prices
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/cz_energy_spot_prices/__init__.py", line 24, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, ['sensor'])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms

**Comment by rnovacek** [comment]
@davidvalasek vyřešeno? jak?

**Comment by Fred749** [comment]
Ze zařízení odstranit integraci "Electricity Spot Rate in CZK/kWh" a poté ručně smazat z custom_components "cz_energy_spot_prices". Znovu stáhnout z https://github.com/rnovacek/homeassistant_cz_energy_spot_prices a nahrát do custom_components, přidat integraci Electricity Spot Rate in CZK/kWh a restartovat HA.

**Comment by rnovacek** [comment]
ok, čili aktualizovat na nejnovější verzi, díky za info. Mimochodem už jde instalovat i z HACS.
