### ISSUE TITLE
Nefunkční integrace po aktualizaci HA

### ISSUE THREAD

**Issue by Sten7777** [rnovacek/homeassistant_cz_energy_spot_prices#24]
Ahoj,
přestala mi fungovat integrace po aktualizaci HA na poslední verzi.
Chyba v logu:
Logger: homeassistant.config_entries
Source: custom_components/cz_energy_spot_prices/__init__.py:31
Integration: Czech Energy Spot Prices ([documentation](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices))
First occurred: 18:08:36 (1 occurrences)
Last logged: 18:08:36

Error setting up entry Electricity Spot Rate in CZK/kWh for cz_energy_spot_prices
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/cz_energy_spot_prices/__init__.py", line 31, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, ['sensor'])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

Zkoušel jsem integraci přeinstalovat a to nepomohlo. Prosím o radu jak to opravit?

**Comment by rnovacek** [comment]
Vydal jsem novou verzi, zkuste aktualizovat.

**Comment by Sten7777** [comment]
Jde udělat přímo aktualizace? To jsem nenašel. Tak jsem integraci smazal a znovu nahrál. Problém nevyřešen. Jde někde poznat jestli mám správnou verzi?

**Comment by Sten7777** [comment]
Omlouvám se, nahrával jsem tu původní verzi. Nová verze funguje. Děkuji za rychlou pomoc.

**Comment by rnovacek** [comment]
Super, díky za info.
