### ISSUE TITLE
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by Screemy** [rnovacek/homeassistant_cz_energy_spot_prices#26]
Zdravím,

po posledním updatu HA vyhodila integrace tuto chybu:
`Logger: homeassistant.config_entries
Source: custom_components/cz_energy_spot_prices/__init__.py:24 
Integration: Czech Energy Spot Prices ([documentation](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices)) 
First occurred: 7. května 2023 16:27:06 (1 occurrences) 
Last logged: 7. května 2023 16:27:06

Error setting up entry Electricity Spot Rate in CZK/kWh for cz_energy_spot_prices
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/cz_energy_spot_prices/__init__.py", line 24, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, ['sensor'])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'`

A nespusti se, nejaké napady?

Díly

**Comment by rnovacek** [comment]
Myslím, že nemáte aktuální verzi integrace. Zkuste ji smazat a nainstalovat 0.5.0 z HACS.

**Comment by Screemy** [comment]
Hmm to je zvlástní, protoze tam 0.5.0 v HACS nevidim .... pouze

v0.1.2
v0.1.1
v0.1.0
master 

Zkousel jsem nyni i master, ale bez uspechu

**Comment by rnovacek** [comment]
Divný, 0.1.1 a 0.1.2 tady na githubu ani nevidím v "releases". Můžete zkusit nainstalovat integraci ručně: https://github.com/rnovacek/homeassistant_cz_energy_spot_prices#installation nebo zkusit nějak HACS přemluvit, ať to zkusí stáhnout znovu. A nebo [přeinstalovat HACS](https://community.home-assistant.io/t/unable-to-update-hacs-nor-hacs-integrations/423337/4).

**Comment by Screemy** [comment]
preinstalval jsem hacs beze zmeny ...

jdu zkusit rucne nahodit soubory

**Comment by rnovacek** [comment]
Je to stále problém?

**Comment by rnovacek** [comment]
Předpokládám, že už je to opraveno, jelikož si nikdo nestěžuje. Kdyby se to jestě stalo, tak to prosím znovu otevřete.
