### ISSUE TITLE
Median value

### ISSUE THREAD

**Issue by hipik634** [rnovacek/homeassistant_cz_energy_spot_prices#34]
Hi, I am having issue with cheapest blocks. Sometimes it misses the night. I need to run battery recharge each night + each day (when there is not enough sun). My guess it would be median. And if value is under median, the sensor would go on signaling enable charging (to get over top prices) . Could that be managed or added to sensor set? The idea is to be able to utilize both graph lows, not only the main cheapest block. thanks
![2023-10-13 13_56_40-Victron – Home Assistant](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/30725259/6efbe95d-e0f0-49f0-afff-fb91d40d3f2a)

**Comment by rnovacek** [comment]
Median can be achieved by using `Current Spot Electricity Hour Order`. When it's value is <= 12 it's below the median, otherwise it's above it.

Or maybe I just don't understand the question :)

**Comment by hipik634** [comment]
thanks, I have had issues with working with the hour order, i cannot correctly formulate the automation rules, because the values are in the attributes and i seem not to understand how to create a condition 
condition:
  - condition: state
    entity_id: sensor.current_spot_electricity_hour_order
    attribute:  bellow 12 ?   // values like: "2023-11-02T12:00:00+01:00"
    state: ""  
Can you please give an example, how to create one? something like when current spot price is bellow <12 . Sorry to bother you.

**Comment by rnovacek** [comment]
Sorry for late answer, I missed the notification for this comment.

Try something like this:

```
description: ""
mode: single
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.current_spot_electricity_hour_order
    below: 12
condition: []
action: []
```

`sensor.current_spot_electricity_hour_order` is order of current hour when you sort all hours in a day by the price. So when value of this sensor is below 12, it means the price is below median.
