### ISSUE TITLE
device_class: monetary

### ISSUE THREAD

**Issue by rattkin** [rnovacek/homeassistant_cz_energy_spot_prices#37]
Snažím se přičítat ke spotovým cenám ještě cenu za distribuci podle HDO

nezdá se mi `monetary` u `device_class` Nevím zda je to podporované u HA.
https://github.com/home-assistant/core/issues/86780

asi by měl být `device_class` všude `measurement` protože to není akumulace vydělaných/utracených peněz, ale měření aktuální ceny.

Je to v souboru custom_components/cz_energy_spot_prices/sensor.py:227

Podle mne je to důvod, proč entita `sensor.current_spot_electricity_price` se v apex grafu ukazuje jako NaN
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/910080/399dad93-ac71-45a7-9ee5-bc8578bfc27f)

**Comment by rattkin** [comment]
@ondras12345 děkuji, právě že nevidím chybu a problém má víc lidí.
Updated bylo v 20:00, teď je 20:38, každou hodinu to chodí dobře
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/910080/0b4a6999-17ba-4c71-aedd-c13e33c81ddf)

**Comment by ondras12345** [comment]
Ukažte konfiguraci apexcharts grafu

**Comment by ondras12345** [comment]
```
type: custom:apexcharts-card
graph_span: 2d
header:
  show: true
  show_states: true
span:
  start: day
series:
  - entity: sensor.current_spot_electricity_price
    float_precision: 2
    show:
      in_header: raw
    data_generator: |
      return Object.entries(entity.attributes).map(([date, value], index) => {
        return [new Date(date).getTime(), (value + 0.35 + 0.028 + 0.114 )* 1.21];
      });
```
Tohle mi cenu v záhlaví aktuální hodnotu ukazuje:
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/44524735/8b3e4688-ebfa-4bf1-9e21-69592a099f24)


(Home Assistant 2023.10.3, Czech Energy Spot Prices 0.6.1, apexcharts-card v2.0.4)

**Comment by rattkin** [comment]
@ondras12345 když zapnu header, tak se tam ukazuje hodnota spotu, ale HDO je NaN.. obráceně než v zápatí.. 🤷 
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/910080/4ecaaf64-8a67-423a-8e59-cef6c6f970e2)
Váš příklad mi chodí...
Mě to taky ukazuje, ale jen někdy, chvíli, pak tam skočí NaN.
verze software mi sedí.

**Comment by rattkin** [comment]
@ondras12345 tak jsem to rozchodil nějakou manipulací s tím co je/není `raw`
spot musí být `raw` ale hdo nesmí být.
Důvod je v jednotkách, nebo device_class?
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/910080/c7e3b849-4280-401f-b395-96d6b46c96b0)
 hdo: 
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/910080/f2568ae3-07c9-458f-ac15-9b8b51ef4bf0)

**Comment by ondras12345** [comment]
Apexcharts-card `device_class` ani nečte.
Ta HDO entita je `binary_sensor`, takže s `raw` určitě nebude zobrazovat číslo (její stav je "on"/" off"). Tam to NaN možná vzniká kvůli tomu, že je v konfiguraci grafu přidáno `unit` - tu binární hodnoty mít nemají, možná se v takovém případě karta pokouší o  konverzi na číslo. Bez `raw` se asi bere hodnota z `data_generator`, to už číslo je.

Každopádně to není problém s touto integrací. Ta sice chybně používá `device_class: monetary` pro cenu za kWh (takže issue nezavírat), ale to není příčinou vašich problémů.

**Comment by ondras12345** [comment]
U spotu zkuste
```
    show:
      in_header: before_now
```
místo `raw`, pokud chcete zobrazovat přepočítanou cenu z `data_generator`.

**Comment by rattkin** [comment]
@ondras12345 dík já se to časem naučím.
Mám udělat PR který zde odebere `device_class: monetary` ?
mám dát něco jiného místo toho?

**Comment by ondras12345** [comment]
> Mám udělat PR který zde odebere `device_class: monetary` ?

To je otázka na @rnovacek 



> mám dát něco jiného místo toho?

Na [seznamu validních `device_class` pro sensor](https://www.home-assistant.io/integrations/sensor#device-class) nevidím žádnou vhodnou hodnotu, takže asi ne.

**Comment by hipik634** [comment]
ten binary sensor hdo máš jako tabulku, nebo pin sensor? pokud tabulku, prosím vložit. díky
