### ISSUE TITLE
Current Spot Electricity Hour not matching the hour of the day

### ISSUE THREAD

**Issue by pavelmikulka** [rnovacek/homeassistant_cz_energy_spot_prices#39]
Hi Radek, thank you for this integration!
I have had it installed for a couple of weeks and recently I had noticed an oddly low price for an evening, so I analyzed the data and found out the hours and corresponding rates are not being matched to the hour of the day, rather simply to a line order. 
Please see screenshot attached. Is this something you are aware of and can be fixed on my part? I have tried removing and re-adding the integration to no avail.
Thank you.
![OTE_confused_hours](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/31282065/982c1c7c-b244-48f8-9e69-ca3350e7b8e0)

**Comment by pavelmikulka** [comment]
> Hi, did you check sensor.current_spot_electricity_price ?

Hi, yes, I did. The price corresponds with the line timestamp in the datafile (see my original screenshot). So, right now (at 19:09), the readings are:
sensor.current_spot_electricity_hour_order: 22
sensor.current_spot_electricity_price: 152,92

**Comment by kkoouu** [comment]
Well, same numbers here. Current price is  correct ( https://www.ote-cr.cz/cs/kratkodobe-trhy/elektrina/denni-trh?date=2023-10-31) ) and looks like it's the 22nd cheapest ( or 3rd most expensive ) hour today ... maybe I don't understand what you mean or maybe you misunderstood what those numbers represent ?

**Comment by pavelmikulka** [comment]
Well, in that case I have misunderstood the meaning of the hour order, or accidentally, when I was observing the data in the past, the hour order coincided with the current hour, so I assumed that it was simply the order of the hourly price in that day.
Anyway, thank you for the explanation!
