### ISSUE TITLE
Timeout fetching prices

### ISSUE THREAD

**Issue by johnnyhero83** [rnovacek/homeassistant_cz_energy_spot_prices#41]
Ahoj, Dobry den,
Nevím, jestli to děla jen me, ale pravidelně snad každý den obdržím tento timeout. Výpis níže. 
Včera jsem přepisoval všechny soubory v adresáři custom components novými a doufal, ze to pomůže. Bohužel je to stejne. V čem muže být problém?
Jinak Dekuji za výborný nástroj k řízení dle spotovych cen. 

Logger: custom_components.cz_energy_spot_prices.coordinator
Source: helpers/update_coordinator.py:296 
Integration: Czech Energy Spot Prices ([documentation](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices), [issues](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/issues)) 
First occurred: 12:00:10 (1 occurrences) 
Last logged: 12:00:10

Timeout fetching Czech Energy Spot Prices data

**Comment by rnovacek** [comment]
Duplicate of #42
