### ISSUE TITLE
Cheapest X hours blocks - strange behavior

### ISSUE THREAD

**Issue by LubosD** [rnovacek/homeassistant_cz_energy_spot_prices#46]
Zatím jsem na verzi 0.6.0, takže se omlouvám, pokud je to už opravené.

Používám entitu na blok 3 nejlevnějších hodin, ale dělá to občas koniny. Včera ten blok měl 4 hodiny:

![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/878801/9b1ba7ab-cca3-4280-9ceb-8ad59256bd68)

A dneska měl jenom 2:

![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/878801/c0c738cd-67e2-481a-945c-e24f99d9fc04)

Přičemž je navíc na první pohled zřejmé, že to dnes ani nevybralo ty nejlevnější hodiny. Mezi 02:00-04:00 bylo určitě levněji než mezi 00:00-02:00.
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/878801/690cac86-3e1a-4523-b035-de4ddfff55d9)

Potvrzuje to i hour order:
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/878801/bfa0ef3c-7d8a-4f74-b9b8-382444ff6161)

**Comment by kkoouu** [comment]
U me OK:

![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/5188963/13a01a80-ac33-46dc-9360-791e8ea5dbbf)

**Comment by rnovacek** [comment]
U mě je to taky v pohodě. Zkusil bych tedy aktualizovat na poslední verzi a pokud se to bude opakovat, tak přiložit logy.

**Comment by LubosD** [comment]
Vyzkouším, díky za odpovědi.

**Comment by rnovacek** [comment]
@LubosD Už to funguje dle očekávání? Můžeme tuhle issue zavřít?

**Comment by LubosD** [comment]
Zatím podle všeho dobrý, zavírám.
