### ISSUE TITLE
Zaokrouhleni ceny

### ISSUE THREAD

**Issue by valentapat** [rnovacek/homeassistant_cz_energy_spot_prices#50]
dobry den, přidal jsem si panel s aktualni cenou elektriny.
cards:
  - type: gauge
    entity: sensor.current_spot_electricity_price
    name: Cena elektřiny.
    min: 0
    max: 10

vysledek vypada 1,58984 Kč/kWh

pridane ....
template: "{{ (sensor.current_spot_electricity_price | round(1)) }} "
template: "{{ states(sensor.current_spot_electricity_price) | round(1) }} "

nefungují

jak muzu toto cislo zaokrouhlit ?

**Comment by rnovacek** [comment]
```
{{ states('sensor.current_spot_electricity_price') | round(1) }}
```

Tohle mi funguje.

**Comment by valentapat** [comment]
asi delam neco spatne, .... 
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/17265945/22e7fbe0-894c-4d29-9548-9c9f59c96a41)
![image](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/17265945/dd7f9538-763f-440f-a5f3-2a4b65583f4e)

me to nic nedela

**Comment by valentapat** [comment]
Děkuji za postřehy, nevěděl jsem, protože jsem našel diskuse na netu ohledně gauge a zaokrouhlení. Vyřešil jsem to přes pomocnika, diky
