### ISSUE TITLE
Spatne zobrazeni cen (+1 hodina)

### ISSUE THREAD

**Issue by PTiCA1** [rnovacek/homeassistant_cz_energy_spot_prices#51]
Narazilj sem na problem se zobrazenim spravne ceny ze spotu.

Cena se zobrazuje o hodinu spatne. Prikladam obrazek kde je videt nejlevnejsi cena v HA a na OTE

<img width="736" alt="Snímek obrazovky 2024-05-21 v 18 21 09" src="https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/7615801/d6e585b7-ed9f-4834-b436-955497f94db3">

Je to problem jenom u me nebo i u nekoho jineho?

**Comment by PTiCA1** [comment]
Diky za informaci. Takze napriklad dnesni den je spravne?

<img width="1345" alt="Snímek obrazovky 2024-05-28 v 21 25 38" src="https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/7615801/0e982823-b72a-49f8-a40e-8922fcf7c0a8">

**Comment by rnovacek** [comment]
Ano, Hodina 14 na OTE znamená 13:00 - 14:00. Ta tabulka začíná Hodinou 1, takže 0:00 - 1:00.
