### ISSUE TITLE
current price +1h ahead of real price

### ISSUE THREAD

**Issue by martan223** [rnovacek/homeassistant_cz_energy_spot_prices#54]
![obrazek](https://github.com/user-attachments/assets/d4e43b1f-059a-4856-bd96-575d85b9e11f)
![obrazek](https://github.com/user-attachments/assets/2e8a2f7e-85fd-43ca-a5f0-5240925e0d2f)
Hi, i have problem with current price (i am using it to eliminate selling while price is negative). i was comparing to ČEZ and OTE prices - they are correct but they are 1 hour ahead of real prices. 
I have timezone set to +1:00 Prague, so my guess is its caused by summer time.

**Comment by rnovacek** [comment]
I think this is the same problem as was already reported multiple times (https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/issues/48#issuecomment-1872879428, https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/issues/47#issuecomment-1867807593).

OTE prices are indexed from 1, so `1` means 0:00 - 1:00. In your screenshot, the most expensive hour is `15`, which means 14:00 - 15:00 and that also matches the chart.
