### ISSUE TITLE
Integration setting explanation, possibility of adding sensor value?

### ISSUE THREAD

**Issue by Lipown** [rnovacek/homeassistant_cz_energy_spot_prices#6]
Všiml jsem si, že integrace má nastavení:

![obrazek](https://user-images.githubusercontent.com/57076375/210172167-e0dd1b72-78dc-47f2-87aa-4ac28463679f.png)

- Můžu do polí vložit sensor? Mám nízký a vysoký tarif tudiž námam jednotnou dodatečných nákladů
- Co znamená prosím pole "Hodiny nejlevnějšího slouvislého..."

Integrace je skvělá! Díky za ní :)

**Comment by rnovacek** [comment]
Omlouvám se, tyhle nastavení zatím nic nedělají - není to implementováno. Mám to rozdělané, ale nějak zatím není čas.

**Comment by Lipown** [comment]
V pohodě, nespěchejte. Už i tak je ta integrace skvělá! :)

**Comment by rnovacek** [comment]
Nastavení už nějakou dobu fungují, issue zavírám.
