### ISSUE TITLE
Entity not available: czech_energy_spot_prices

### ISSUE THREAD

**Issue by PeetrSt** [rnovacek/homeassistant_cz_energy_spot_prices#60]
Dobrý den,
asi dělám od začátku něco špatně.
Nainstaluji přes HACS, restartuji.
Nikde jsem nenašel, kde zadat jednotky a měnu.
Ceny se nestahují. Vidím pouze entitu Czech Energy Spot Prices update.
děkuji

**Comment by rnovacek** [comment]
Integraci jste v nastavení přidal? 
Něco zajímavého v logu?

**Comment by PeetrSt** [comment]
V zařízení ji vidím pod Hacs. V logu nic není.

V nástrojích pro vývojáře vidím nastavit stav:
entita: update.czech_energy_spot_prices_update
stav: off

Atributy stavu:
auto_update: false
installed_version: 0.6.3
in_progress: false
latest_version: 0.6.3
release_summary: null
release_url: https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/releases/0.6.3
skipped_version: null
title: null
entity_picture: https://brands.home-assistant.io/_/cz_energy_spot_prices/icon.png
friendly_name: Czech Energy Spot Prices update
supported_features: 23

**Comment by kkoouu** [comment]
entita se jmenuje sensor.current_spot_electricity_price, tu taky nevidite ?

**Comment by PeetrSt** [comment]
nevidím

**Comment by rnovacek** [comment]
HACS s tím vlastně nemá nic moc společného, je to jen systém, jak tu integraci instalovat. 

Je potřeba jít do Nastavení -> Zařízení a služby -> Přidat integraci -> tam ji vyhledat a projít instalací.

**Comment by PeetrSt** [comment]
Začátečnická chyba při instalaci.
Nastavení -> Zařízení a služby -> Přidat integraci -> tam ji vyhledat a projít instalací   funguje

děkuji moc
