### ISSUE TITLE
Support for TOU distribution rates

### ISSUE THREAD

**Issue by prehor** [rnovacek/homeassistant_cz_energy_spot_prices#61]
Tohle mi přišlo jako skvělá idea jak se vypořádat s dvoutarifní cenou za distribuci elektřiny, ale s uzavřením #5 se mi zdá, že zapadla:

> Integrace bude mít v nastavení template, který se aplikuje na každou hodinu spotové ceny. V podstatě funkce, která bere dva argumenty: cenu na spotu a čas a vrací cenu pro prodej.
> 
> Něco jako
> 
> ```
> def cena_prodej(cena, cas):
>     if cas.hour in [8, 9, 12, 14, 15, 18]: # hodiny vysokého tarifu
>         distribuce = 1.5 # VT
>     else:
>         distribuce = 0.4 # NT
>     return cena + distribuce
> ```
> 
> Bude to (jinja2) template ne python, ale pro ukázku to snad stačí. Tahle výsledná nákupní cena se pak bude používat těch blokových senzorech. Bude to fungovat pro váš usecase?

_Originally posted by @rnovacek in https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/issues/5#issuecomment-1422435576_

**Comment by prehor** [comment]
Díval jsem se jak se využívají parametry/templaty ceny nákupu a prodeje a zadané hodnoty ovlivňují pouze cenu pro aktuální hodinu, ale nejsou obsaženy v seznamu cen pro tento a následující den, takže seřazený seznam cen i bloky nejlevnějších a nejdražších hodin neobsahují skutečné ceny nákupu/prodeje, ale čisté spotové ceny. Asi by se to vyřešit seznam cen v templatu jako je ukázáno ve #49, ale další funkcionalita - seřazený seznam cen a bloky cen by byly mnohem složitější.

Mohlo by to fungovat takto:
* Třída `SpotRateElectricitySensor`
  * Přidat konstruktor `__init__` s volitelným parametrem `template_code: Optional[str]` podle konstruktoru třídy `TemplatePriceSensor`
  * Přidat metodu `def get_hour_price(self, value: float, hour: datetime) -> float:` která vrátí `value` a pokud existuje `template` tak ji nejprve upraví pomocí templatu, kterému kromě `value` předá navíc i `hour` v `datetime` formátu
  * Upravit metodu `update` aby používala `get_hour_price` pro získání ceny v danou hodinu i pro aktuální hodinu
* Použít pro senzory `sensor.current_spot_electricity_buy_price` a `sensor.current_spot_electricity_sell_price` třídu `SpotRateElectricitySensor` s příslušnými templaty
* Přidat senzory 
  * `sensor.current_spot_electricity_buy_hour_order`
  * `sensor.tomorrow_spot_electricity_buy_hour_order`
  * `sensor.spot_cheapest_electricity_buy_today`
  * `sensor.spot_cheapest_electricity_buy_tomorrow`
  * `sensor.spot_electricity_buy_is_cheapest`
  * `sensor.spot_electricity_is_cheapest_X_hours_block`
  * `sensor.spot_most_expensive_electricity_buy_today`
  * `sensor.spot_most_expensive_electricity_buy_tomorrow`
  A stejné senzory pro `_sell_`

Zdálo se mi, že by to nemuselo být zase až tak složité implementovat a bylo by to kompatibilní se stávající verzí. Moje znalost Pythonu se bohužel limitně blíží nule,  zatím se seznamuju se syntaxí abych byl schopen kód alespoň přečíst, takže s implementací moc nemůžu :-(

**Comment by rnovacek** [comment]
This is now done in 0.7.0b0.
