### ISSUE TITLE
HA upgrade 2023.2 issues warning

### ISSUE THREAD

**Issue by PetrMedek** [rnovacek/homeassistant_cz_energy_spot_prices#9]
Pls be so kind and check this. Thx
Petr

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77 
First occurred: 19:10:49 (1 occurrences) 
Last logged: 19:10:49

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for cz_energy_spot_prices using this method at custom_components/cz_energy_spot_prices/__init__.py, line 31: hass.config_entries.async_setup_platforms(config_entry, ['sensor'])

**Comment by rnovacek** [comment]
Fixed now.
